apiVersion: v1
kind: Pod
metadata:
	name: nonroot-nginx-pod
spec:
	containers:
  - name: nginx
		image: nginx:1.20
    securityContext:
			runAsUser: 1000
			privileged: false
			allowPrivilegeEscalation: false
